log_format prometheus_json escape=json
'{'
    '"host":"$host",'
    '"method":"$request_method",'
    '"uri":"$uri",'
    '"status":$status,'
    '"request_time":$request_time,'
    '"bytes_sent":$bytes_sent,'
    '"request_length":$request_length,'
    '"upstream_response_time":"$upstream_response_time"'
'}';

server {
    listen 3000;
    server_name _;
    root /usr/share/nginx/html;

    access_log /var/log/nginx/exporter-access.log prometheus_json;

    location / {
        try_files $uri $uri/ $uri.html =404;
    }

    location /_next/static/ {
        access_log off;
        expires 365d;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }
}