groups:
- name: test-alerts
  rules:
    - alert: TestEmailNotification
      expr: vector(1) # Always triggers
      for: 10s
      labels:
        severity: critical
      annotations:
        summary: "Test Alert"
        description: "This is a test alert to verify email notifications."
