global:
  # SMTP server details
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'muzicluver603@gmail.com'

  # SMTP credentials loaded from Docker secrets
  smtp_auth_username: 'muzicluver603@gmail.com'
  smtp_auth_password_file: '/run/secrets/alertmanager_smtp_password'

  # Ensure TLS is used
  smtp_require_tls: true

route:
  # Default route for all alerts
  receiver: 'email-notification'

  # Match specific labels for routing if needed
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'email-notification'
    email_configs:
      - to: 'rohit.mmm1996@gmail.com' # Replace with the recipient's email