global: 

    smtp_smarthost: 'smtp.gmail.com:587'
    smtp_from: 'muzicluver603@gmail.com'
    smtp_auth_username: '{{ with (readFile "/run/secrets/alertmanager_smtp_user") }}{{ . }}{{ end }}'
    smtp_auth_password: '{{ with (readFile "/run/secrets/alertmanager_smtp_password") }}{{ . }}{{ end }}'
    smtp_require_tls: true

    resolve_timeout: 1m
    receivers:
    - name: 'email-notification'
      email_configs:
        - to: 'rohit.mmm1996@gmail.com'

    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'cluster', 'service']

    # route:
    # receiver: 'slack-notifications'

    # receivers:
    #  - name: 'slack-notifications'
    # slack_configs:
    #   - channel: '#monospaced'
    #     send_resolved: true
    #     icon_url: https://avatars3.githubusercontent.com/u/3380462
    #     title: |-
    #       [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
    #       {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
    #         {{" "}}(
    #         {{- with .CommonLabels.Remove .GroupLabels.Names }}
    #           {{- range $index, $label := .SortedPairs -}}
    #             {{ if $index }}, {{ end }}
    #             {{- $label.Name }}="{{ $label.Value -}}"
    #           {{- end }}
    #         {{- end -}}
    #         )
    #       {{- end }}
    #     text: >-
    #       {{ range .Alerts -}}
    #       *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
    #       *Description:* {{ .Annotations.description }}
    #       *Details:*
    #         {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
    #         {{ end }}
    #       {{ end }}