version: '3.9'

services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    restart: always
    depends_on:
      - backend
  backend:
    container_name: backend
    healthcheck:
      test: ["CMD", "curl", '-f', 'http://localhost:4000/health']
      interval: 1m30s
      timeout: 30s
      retries: 5
    image: backend
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://rohit:monospaced@db:5432/monospaced?schema=public
      - EMAIL=rohit.212@icloud.com
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: rohit
      PGUSER: rohit
      POSTGRES_PASSWORD: monospaced
      POSTGRES_DB: monospaced
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rohit -d monospaced"]
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init/:/docker-entrypoint-initdb.d/

volumes:
  pgdata: {}