export const ErrorCodes = {
  HTTP_CLIENT_ERROR: 'HTTP_CLIENT_ERROR',
  HTTP_SERVER_ERROR: 'HTTP_SERVER_ERROR',
  HTTP_TIMEOUT_ERROR: 'HTTP_TIMEOUT_ERROR',
  HTTP_CANCELLED_ERROR: 'HTTP_CANCELLED_ERROR',
  HTTP_UNKNOWN_ERROR: 'HTTP_UNKNOWN_ERROR',
}
