global:
  scrape_interval: "1m"
  evaluation_interval: "1m"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"
rule_files:
  - "/etc/alertmanager/alert.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - "prometheus:9090"
    
  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    scrape_interval: 15s
    static_configs:
      - targets: ['node-exporter:9100']