global:
  scrape_interval: "1m"

scrape_configs:
  - job_name: reverse-proxy
    static_configs:
      - targets:
        - "reverse-proxy:9090"
    
  - job_name: node-exporter
    dns_sd_configs:
      - names:
        - 'tasks.monitoring_node-exporter'
        type: 'A'
        port: 9100

  - job_name: cadvisor
    dns_sd_configs:
      - names:
        - 'tasks.monitoring_cadvisor'
        type: 'A'
        port: 8080