global:
  scrape_interval: "1m"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - "prometheus:9090"
    
  - job_name: 'cadvisor'
    scrape_interval: 5s
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    scrape_interval: 5s
    dns_sd_configs:
    - names:
      - 'tasks.exporter'
      type: 'A'
      port: 9100