receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}

exporters:
  prometheus:
    endpoint: "0.0.0.0:8888"
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  logging: # Add debug logging
    verbosity: detailed
    sampling_initial: 1
    sampling_thereafter: 1

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
