receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  prometheus:
    endpoint: "0.0.0.0:8888"
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  debug: # Replaced logging with debug exporter
    verbosity: detailed

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

service:
  telemetry:
    logs:
      level: "debug"
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]  # Updated to use debug exporter
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
