ports:
  web:
    port: 80
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
    hostPort: 80

  websecure:
    port: 443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
    hostPort: 443

additionalArguments:
  - "--api.dashboard=true"
  - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
  - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
  - "--certificatesresolvers.le.acme.httpchallenge=true"
  - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
  - "--certificatesresolvers.le.acme.email=rohit.mmm1996@gmail.com"
  - "--certificatesresolvers.le.acme.storage=/data/acme.json"

deployment:
  enabled: true

service:
  enabled: false  # 🚫 disables LoadBalancer/NodePort service

ingressClass:
  enabled: true
  isDefaultClass: true
