ports:
  web:
    port: 80
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
    hostPort: 80

  websecure:
    port: 443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
    hostPort: 443

additionalArguments:
  - "--api.dashboard=true"
  - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
  - "--entryPoints.web.http.redirections.entryPoint.scheme=https"

deployment:
  enabled: true
  hostNetwork: true

service:
  enabled: false  # 🚫 disables LoadBalancer/NodePort service

ingressClass:
  enabled: true
  isDefaultClass: true
