annotations:
  cert-manager.io/cluster-issuer: letsencrypt-prod
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: monospaced
spec:
  rules:
  - host: rohitpotato.xyz
    http:
      paths:
      - backend:
          service:
            name: frontend
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - rohitpotato.xyz
    secretname: letsencrypt-prod