export const andyPrismTheme = {
  'code[class*="language-"]': {
    color: '#3C334D',
    background: 'none',
    fontFamily: '"SF Mono", Monaco, Inconsolata, "Roboto Mono", monospace',
    fontSize: '0.875rem',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.65',
    tabSize: 2,
    hyphens: 'none',
  },
  'pre[class*="language-"]': {
    color: '#3C334D',
    background: 'none',
    fontFamily: '"SF Mono", Monaco, Inconsolata, "Roboto Mono", monospace',
    fontSize: '0.875rem',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    lineHeight: '1.65',
    tabSize: 2,
    hyphens: 'none',
  },
  'comment': { color: '#8A7FA1' },
  'prolog': { color: '#8A7FA1' },
  'doctype': { color: '#8A7FA1' },
  'cdata': { color: '#8A7FA1' },
  'punctuation': { color: '#6A5B88' },
  'namespace': { opacity: 0.7 },
  'property': { color: '#5932E5' },
  'tag': { color: '#5932E5' },
  'boolean': { color: '#5932E5' },
  'number': { color: '#006A7D' },
  'constant': { color: '#006A7D' },
  'symbol': { color: '#006A7D' },
  'deleted': { color: '#A33645' },
  'selector': { color: '#6E4FD9' },
  'attr-name': { color: '#6E4FD9' },
  'string': { color: '#3E7A34' },
  'char': { color: '#3E7A34' },
  'builtin': { color: '#3E7A34' },
  'inserted': { color: '#3E7A34' },
  'operator': { color: '#5A4C79' },
  'entity': { color: '#5A4C79' },
  'url': { color: '#5A4C79' },
  'atrule': { color: '#7A44C5' },
  'attr-value': { color: '#3E7A34' },
  'keyword': { color: '#7A44C5' },
  'function': { color: '#4F38B4' },
  'class-name': { color: '#4F38B4' },
  'regex': { color: '#AD7D00' },
  'important': { color: '#7A44C5', fontWeight: 600 },
  'variable': { color: '#4F38B4' },
  'important2': { color: '#7A44C5' },
}
