export const andyPrismTheme = {
  'code[class*="language-"]': {
    color: '#d4d0c8',
    background: 'none',
    fontFamily: '"SF Mono", Monaco, Inconsolata, "Roboto Mono", monospace',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    tabSize: 2,
    hyphens: 'none',
  },
  'pre[class*="language-"]': {
    color: '#d4d0c8',
    background: 'none',
    fontFamily: '"SF Mono", Monaco, Inconsolata, "Roboto Mono", monospace',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    wordWrap: 'normal',
    tabSize: 2,
    hyphens: 'none',
  },
  'comment': { color: '#7a7368', fontStyle: 'italic' },
  'prolog': { color: '#7a7368', fontStyle: 'italic' },
  'doctype': { color: '#7a7368' },
  'cdata': { color: '#7a7368' },
  'punctuation': { color: '#8a8580' },
  'namespace': { opacity: 0.7 },
  'property': { color: '#9aabff' },
  'tag': { color: '#9aabff' },
  'boolean': { color: '#c4a882' },
  'number': { color: '#c4a882' },
  'constant': { color: '#c4a882' },
  'symbol': { color: '#c4a882' },
  'deleted': { color: '#d48484' },
  'selector': { color: '#b8a88a' },
  'attr-name': { color: '#b8c8e8' },
  'string': { color: '#a8c7a0' },
  'char': { color: '#a8c7a0' },
  'builtin': { color: '#a8c7a0' },
  'inserted': { color: '#a8c7a0' },
  'operator': { color: '#9a9590' },
  'entity': { color: '#9a9590' },
  'url': { color: '#9aabff' },
  'atrule': { color: '#b8a88a' },
  'attr-value': { color: '#a8c7a0' },
  'keyword': { color: '#b8a88a' },
  'function': { color: '#9aabff' },
  'class-name': { color: '#9aabff' },
  'regex': { color: '#c4a882' },
  'important': { color: '#b8a88a', fontWeight: 600 },
  'variable': { color: '#d4d0c8' },
  'important2': { color: '#b8a88a' },
}
