apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
  namespace: monospaced
annotations:
  cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
      - api.rohitpotato.xyz
      secretname: letsencrypt-prod
  rules:
    - host: api.rohitpotato.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80
