name: Deploy monospaced

on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  actions: read
  attestations: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build_and_deploy:
    name: Build and Publish Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login into registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push frontend
        run: |
          docker buildx build --file ./frontend/frontend.dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:latest --push ./frontend

      - name: Build and push backend
        run: |
          docker buildx build --file ./backend/backend.dockerfile --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend:latest --push ./backend
  # install cert manager, give certificate to the cluser
  # apply ingress, service, deployment
  pull_and_deploy_image:
    needs: build_and_deploy
    name: Pull and Deploy Image
    runs-on: ubuntu-latest
    steps:
      - name: "Execute commands on VPS"
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/monospaced-stack
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            git pull
            kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.17.2/cert-manager.yaml  
            kubectl apply -f k3s/cert-manager/cluster-issuer.yaml
            kubectl apply -f k3s/ --recursive
